<?php

/**
 * Mux PHP - Copyright 2019 Mux Inc.
 * NOTE: This file is auto generated. Do not edit this file manually.
 */

namespace MuxPhp;

use PHPUnit\Framework\TestCase;

/**
 * CreateUploadRequestTest Class Doc Comment
 *
 * @category    Class
 * @description CreateUploadRequest
 * @package     MuxPhp
 */
class CreateUploadRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateUploadRequest"
     */
    public function testCreateUploadRequest()
    {
    }

    /**
     * Test attribute "timeout"
     */
    public function testPropertyTimeout()
    {
    }

    /**
     * Test attribute "cors_origin"
     */
    public function testPropertyCorsOrigin()
    {
    }

    /**
     * Test attribute "new_asset_settings"
     */
    public function testPropertyNewAssetSettings()
    {
    }
}
