<?php

/**
* Mux PHP - Copyright 2019 Mux Inc.
* NOTE: This file is auto generated. Do not edit this file manually.
*/

namespace MuxPhp;

use PHPUnit\Framework\TestCase;

/**
 * InputSettingsOverlaySettingsTest Class Doc Comment
 *
 * @category    Class
 * @description InputSettingsOverlaySettings
 * @package     MuxPhp
 */
class InputSettingsOverlaySettingsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InputSettingsOverlaySettings"
     */
    public function testInputSettingsOverlaySettings()
    {
    }

    /**
     * Test attribute "vertical_align"
     */
    public function testPropertyVerticalAlign()
    {
    }

    /**
     * Test attribute "vertical_margin"
     */
    public function testPropertyVerticalMargin()
    {
    }

    /**
     * Test attribute "horizontal_align"
     */
    public function testPropertyHorizontalAlign()
    {
    }

    /**
     * Test attribute "horizontal_margin"
     */
    public function testPropertyHorizontalMargin()
    {
    }

    /**
     * Test attribute "width"
     */
    public function testPropertyWidth()
    {
    }

    /**
     * Test attribute "height"
     */
    public function testPropertyHeight()
    {
    }

    /**
     * Test attribute "opacity"
     */
    public function testPropertyOpacity()
    {
    }
}
