<?php

/**
* Mux PHP - Copyright 2019 Mux Inc.
* NOTE: This file is auto generated. Do not edit this file manually.
*/

namespace MuxPhp;

use PHPUnit\Framework\TestCase;

/**
 * ListFiltersResponseDataTest Class Doc Comment
 *
 * @category    Class
 * @description ListFiltersResponseData
 * @package     MuxPhp
 */
class ListFiltersResponseDataTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ListFiltersResponseData"
     */
    public function testListFiltersResponseData()
    {
    }

    /**
     * Test attribute "basic"
     */
    public function testPropertyBasic()
    {
    }

    /**
     * Test attribute "advanced"
     */
    public function testPropertyAdvanced()
    {
    }
}
