<?php

/**
* Mux PHP - Copyright 2019 Mux Inc.
* NOTE: This file is auto generated. Do not edit this file manually.
*/

namespace MuxPhp;

use PHPUnit\Framework\TestCase;

/**
 * LiveStreamTest Class Doc Comment
 *
 * @category    Class
 * @description LiveStream
 * @package     MuxPhp
 */
class LiveStreamTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LiveStream"
     */
    public function testLiveStream()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "stream_key"
     */
    public function testPropertyStreamKey()
    {
    }

    /**
     * Test attribute "active_asset_id"
     */
    public function testPropertyActiveAssetId()
    {
    }

    /**
     * Test attribute "recent_asset_ids"
     */
    public function testPropertyRecentAssetIds()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "playback_ids"
     */
    public function testPropertyPlaybackIds()
    {
    }

    /**
     * Test attribute "new_asset_settings"
     */
    public function testPropertyNewAssetSettings()
    {
    }

    /**
     * Test attribute "passthrough"
     */
    public function testPropertyPassthrough()
    {
    }

    /**
     * Test attribute "reconnect_window"
     */
    public function testPropertyReconnectWindow()
    {
    }
}
