<?php

/**
 * Mux PHP - Copyright 2019 Mux Inc.
 * NOTE: This file is auto generated. Do not edit this file manually.
 */

namespace MuxPhp;

use PHPUnit\Framework\TestCase;

/**
 * UpdateAssetMP4SupportRequestTest Class Doc Comment
 *
 * @category    Class
 * @description UpdateAssetMP4SupportRequest
 * @package     MuxPhp
 */
class UpdateAssetMP4SupportRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UpdateAssetMP4SupportRequest"
     */
    public function testUpdateAssetMP4SupportRequest()
    {
    }

    /**
     * Test attribute "mp4_support"
     */
    public function testPropertyMp4Support()
    {
    }
}
