<?php

/**
 * Mux PHP - Copyright 2019 Mux Inc.
 * NOTE: This file is auto generated. Do not edit this file manually.
 */

namespace MuxPhp;

use PHPUnit\Framework\TestCase;

/**
 * VideoViewEventTest Class Doc Comment
 *
 * @category    Class
 * @description VideoViewEvent
 * @package     MuxPhp
 */
class VideoViewEventTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "VideoViewEvent"
     */
    public function testVideoViewEvent()
    {
    }

    /**
     * Test attribute "viewer_time"
     */
    public function testPropertyViewerTime()
    {
    }

    /**
     * Test attribute "playback_time"
     */
    public function testPropertyPlaybackTime()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "event_time"
     */
    public function testPropertyEventTime()
    {
    }
}
