<?php
/**
 * AssetsApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  MuxPhp
 * @author   Mux API team
 * @link     https://docs.mux.com
 */

/**
 * Mux API
 *
 * Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MuxPhp\Test\Api;

use \MuxPhp\Configuration;
use \MuxPhp\ApiException;
use \MuxPhp\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AssetsApiTest Class Doc Comment
 *
 * @category Class
 * @package  MuxPhp
 * @author   Mux API team
 * @link     https://docs.mux.com
 */
class AssetsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createAsset
     *
     * Create an asset.
     *
     */
    public function testCreateAsset()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createAssetPlaybackId
     *
     * Create a playback ID.
     *
     */
    public function testCreateAssetPlaybackId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createAssetTrack
     *
     * Create an asset track.
     *
     */
    public function testCreateAssetTrack()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteAsset
     *
     * Delete an asset.
     *
     */
    public function testDeleteAsset()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteAssetPlaybackId
     *
     * Delete a playback ID.
     *
     */
    public function testDeleteAssetPlaybackId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteAssetTrack
     *
     * Delete an asset track.
     *
     */
    public function testDeleteAssetTrack()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAsset
     *
     * Retrieve an asset.
     *
     */
    public function testGetAsset()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAssetInputInfo
     *
     * Retrieve asset input info.
     *
     */
    public function testGetAssetInputInfo()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getAssetPlaybackId
     *
     * Retrieve a playback ID.
     *
     */
    public function testGetAssetPlaybackId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAssets
     *
     * List assets.
     *
     */
    public function testListAssets()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateAssetMasterAccess
     *
     * Update master access.
     *
     */
    public function testUpdateAssetMasterAccess()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateAssetMp4Support
     *
     * Update MP4 support.
     *
     */
    public function testUpdateAssetMp4Support()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
