<?php
/**
 * ExportsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  MuxPhp
 */

/**
 * Mux PHP - Copyright 2019 Mux Inc.
 * NOTE: This file is auto generated. Do not edit this file manually.
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MuxPhp;

use \MuxPhp\Configuration;
use \MuxPhp\ApiException;
use \MuxPhp\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ExportsApiTest Class Doc Comment
 *
 * @category Class
 * @package  MuxPhp
 */
class ExportsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for listExports
     *
     * List property video view export links.
     *
     */
    public function testListExports()
    {
    }
}
