<?php
/**
 * MetricsApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  MuxPhp
 * @author   Mux API team
 * @link     https://docs.mux.com
 */

/**
 * Mux API
 *
 * Mux is how developers build online video. This API encompasses both Mux Video and Mux Data functionality to help you build your video-related projects better and faster than ever before.
 *
 * The version of the OpenAPI document: v1
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace MuxPhp\Test\Api;

use \MuxPhp\Configuration;
use \MuxPhp\ApiException;
use \MuxPhp\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MetricsApiTest Class Doc Comment
 *
 * @category Class
 * @package  MuxPhp
 * @author   Mux API team
 * @link     https://docs.mux.com
 */
class MetricsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getMetricTimeseriesData
     *
     * Get metric timeseries data.
     *
     */
    public function testGetMetricTimeseriesData()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOverallValues
     *
     * Get Overall values.
     *
     */
    public function testGetOverallValues()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listAllMetricValues
     *
     * List all metric values.
     *
     */
    public function testListAllMetricValues()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listBreakdownValues
     *
     * List breakdown values.
     *
     */
    public function testListBreakdownValues()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listInsights
     *
     * List Insights.
     *
     */
    public function testListInsights()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
